### ISSUE TITLE
scanStopCallback is not defined

### ISSUE THREAD

**Issue by KuLi** [espruino/EspruinoHub#74]
On a fresh install i get follwing error:

```
/home/pi/EspruinoHub/lib/discovery.js:202
    if (scanStopCallback) {
    ^

ReferenceError: scanStopCallback is not defined
    at Noble.<anonymous> (/home/pi/EspruinoHub/lib/discovery.js:202:5)
    at Noble.emit (events.js:198:13)
    at Noble.onScanStop (/home/pi/EspruinoHub/node_modules/@abandonware/noble/lib/noble.js:164:8)
    at NobleBindings.emit (events.js:198:13)
    at NobleBindings.onScanStop (/home/pi/EspruinoHub/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:133:8)
    at Gap.emit (events.js:198:13)
    at Gap.onLeScanEnableSetCmd (/home/pi/EspruinoHub/node_modules/@abandonware/noble/lib/hci-socket/gap.js:86:12)
    at Hci.emit (events.js:198:13)
    at Hci.onSocketData (/home/pi/EspruinoHub/node_modules/@abandonware/noble/lib/hci-socket/hci.js:534:12)
    at BluetoothHciSocket.emit (events.js:198:13)
```

Can you help me?

**Comment by gfwilliams** [comment]
Sorry about this - looks like it didn't happen in testing because during my testing, scanning only stopped in response to a `stopScan` call. Thanks for the PR!
